"""empty message

Revision ID: 891186e2462e
Revises: eac02a545fa7
Create Date: 2020-12-26 22:21:08.715394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891186e2462e'
down_revision = 'eac02a545fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('start_time', sa.Date(), nullable=False))
    op.drop_column('Shows', 'show_start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('show_start_time', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('Shows', 'start_time')
    # ### end Alembic commands ###
